# -*- coding: utf-8 -*-
"""IC_Parte1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oryCh5o2z4k80c0LwxlbASHsGqslsUbV

## Análise exploratória e pré processamento dos dados
"""

!pip install efficient-apriori

import pandas as pd #exploração geral
import numpy as np #segmentação idades
from efficient_apriori import apriori #apriori
import matplotlib.pyplot as plt #gráficos
import seaborn as sns # Visualização

from google.colab import drive #importando da biblioteca do google colab a função drive para conseguir ler a tabela que eu subir no meu drive
drive.mount('/content/drive')

"""> "O pandas, com copy_on_write=True, cria uma cópia dos dados de df_sliced e faz a alteração nela, em vez de alterar diretamente o DataFrame original. Isso evita o SettingWithCopyWarning porque agora não há a possibilidade de alterar uma fatia do DataFrame de forma inesperada — a alteração acontece em uma cópia da fatia, e não no DataFrame original."

Acredito que teve atualização no pandas mas não consegui entender direito, porque até segunda o código funcionava perfeitamente





"""

pd.options.mode.copy_on_write = True

df_dados = pd.read_csv('/content/drive/MyDrive/IC/base_porto_alegre.csv', encoding='latin1', sep=';', low_memory=False)
#tive que usar esse encoding pois o colab não estava conseguindo ler por causa do idioma padrão que provavelmente não suportava ç
#o sep para separar com ; ao inves de , como é feito em outros paises
#low_memory=False, tive que usar provavelmente por causa da nova atualização

df_dados.info()

df_dados.tail()

df_dados['Nome Profissão'].value_counts()

"""
Selecionando apenas colunas relevantes para análise: sexo, idade, raça/cor,Nome Profissão, grau de instrução, estado civil, Código da Topografia, código da Morfologia, TNM e indicador de caso raro"""

df_transformado = df_dados[['Sexo', 'Idade', 'Raca/Cor', 'Nome Profissão', 'Grau de Instrução', 'Estado Civil', 'Código da Topografia']]

df_transformado.head()

df_transformado['Estado Civil'].value_counts()

"""tirando \t da coluna Nome Profissão"""

df_transformado['Nome Profissão'] = df_transformado['Nome Profissão'].str.replace('\t', '', regex=False)

df_transformado.head()

"""tirando pessoas que são 'SEM INFORMAÇÃO' na coluna Sexo, Idade e Raca/Cor


"""

#criando cópia
df_semInfo = df_transformado.copy()

#loop para limpar
for coluna in df_semInfo.columns:
    df_semInfo = df_semInfo[df_semInfo[coluna] != 'SEM INFORMAÇÃO']
    df_semInfo = df_semInfo[df_semInfo[coluna] != 'IGNORADO']

#voltando para o original
df_transformado = df_semInfo

df_transformado['Estado Civil'].value_counts()

#tirar toda linha que está com pelo menos uma coluna vazia
df_transformado = df_transformado.dropna()

df_transformado.info()

df_transformado['Código da Topografia'].value_counts()
#verifiquei em todas as colunas se limpou mesmo

"""transformando as idades em faixas etárias"""

df_transformado['Idade'].describe()

"""de acordo com o INCA + ESTUDO ACIMA: (está no notion - pasta IC)

0 - 19 - criança/adolescente

20 - 29 jovem adulto

30 - 39 - adulto

40 - 69

70 +
"""

import numpy as np
lst_ranges = []
for i in range(0, 100, 5):
    lst_ranges.append((i, i + 4))
lst_ranges.append((100, np.inf))

ranges = pd.IntervalIndex.from_tuples(lst_ranges, closed = 'both')

df_transformado['Faixa Etária'] = pd.cut(df_transformado['Idade'], bins=ranges)

df_transformado['Faixa Etária'].value_counts()

#tirando a coluna idade
df_transformado.drop(columns=['Idade'], inplace=True)

"""tirando valores únicos
#criando cópia para não dar problema
df_filtrado = df_transformado.copy()

#passa coluna por coluna
for coluna in df_filtrado.columns:
    #conto os value counts e armazeno na variavel value counts
    value_counts =  df_filtrado[coluna].value_counts()

    #pego os valores que aparecem apenas 1 vez
    unique_values = value_counts[value_counts == 1].index

    #remove todos que não estão no unique_values, vulgo, os que aparecem só uma vez
    df_filtrado = df_filtrado[~df_filtrado[coluna].isin(unique_values)]

#atualizando o df
df_transformado = df_filtrado
"""

# Remove o último dígito de cada código no campo 'Código da Topografia'
df_transformado['Código da Topografia'] = df_transformado['Código da Topografia'].str[:-1]

# Conta os valores por categoria (CXX) sem considerar o último dígito
value_counts = df_transformado['Código da Topografia'].value_counts()

# Exibe os resultados
print(value_counts)

"""se ficarem muitas regras voltar esse código: # Criando cópia para não dar problema
df_filtrado = df_transformado.copy()

rows_before_filtering = len(df_filtrado)
print(f"Número de linhas antes da filtragem: {rows_before_filtering}")

# Calculando o limite de frequência para 1% do dataset
threshold = len(df_filtrado) * 0.01

# Passa coluna por coluna
for coluna in df_filtrado.columns:
    # Para colunas categóricas (object ou category dtype)
    if df_filtrado[coluna].dtype == 'object' or isinstance(df_filtrado[coluna].dtype, pd.CategoricalDtype):
        # Conto os value counts
        value_counts = df_filtrado[coluna].value_counts()

        # Pego os valores que aparecem menos que o limite de 1%
        low_frequency_values = value_counts[value_counts < threshold].index

        # Remove todas as linhas onde a coluna contém um valor de baixa frequência
        df_filtrado = df_filtrado[~df_filtrado[coluna].isin(low_frequency_values)]

# Atualizando o df original
df_transformado = df_filtrado

rows_after_filtering = len(df_transformado)
print(f"Número de linhas após a filtragem: {rows_after_filtering}")

No CID-10: CXXY - CXX representa o cancer e Y origem
Como eu analiso? retiro o ultimo digito do código e ai sim filtro? FIZ ISSO
"""

df_transformado['Código da Topografia'].value_counts()

"""base de dados bem equilibrada

"""

df_transformado['Sexo'].value_counts()

"""Distribuição da raça da população

distribuição dos sexos na população

https://www.dio.me/articles/8-graficos-fundamentais-para-data-science-utilizando-python

---
"""

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 8))
counts = df_transformado['Raca/Cor'].value_counts()

# Criando um gráfico de barras
sns.barplot(x=counts.index, y=counts.values, hue=counts.index, palette='rocket', legend=False)

plt.title('Distribuição de pacientes por Raça/cor')
plt.ylabel('Quantidade')
plt.xlabel('Raça/Cor')

# Adicionando as porcentagens no topo das barras
total = counts.sum()
for i, v in enumerate(counts.values):
    plt.text(i, v + (total*0.01), f'{(v/total)*100:.1f}%', ha='center')

plt.show()

plt.figure(figsize=(10, 8))
# Definindo a paleta 'rocket'
cool_colors = sns.color_palette('rocket', len(df_transformado['Raca/Cor'].value_counts()))
plt.pie(df_transformado['Sexo'].value_counts(), labels=df_transformado['Sexo'].value_counts().index, autopct='%1.1f%%', colors=cool_colors, textprops={'color': 'white'})
plt.title('Distribuição da população por sexo')
plt.legend()
plt.show()

plt.figure(figsize=(10, 8))
counts = df_transformado['Faixa Etária'].value_counts(normalize=True).mul(100).sort_index(ascending=True)

sns.barplot(x=counts.index.astype(str), y=counts.values, hue=counts.index.astype(str), palette='rocket', legend=False)

plt.title('Distribuição da Faixa Etária dos pacientes')
plt.xlabel('Faixa Etária')
plt.ylabel('Porcentagem')
plt.xticks(rotation=45, ha='right')

for index, value in enumerate(counts.values):
    plt.text(index, value + 0.1, f'{value:.1f}%', ha='center', va='bottom', fontsize=9)

plt.tight_layout()
plt.show()

plt.figure(figsize=(12, 7))

counts_df = df_transformado.groupby('Faixa Etária', observed=False)['Raca/Cor'].value_counts(normalize=True).mul(100).rename('percentage').reset_index()

sns.barplot(data=counts_df, x='Faixa Etária', y='percentage', hue='Raca/Cor', palette='rocket')

plt.title('Distribuição de Raça/Cor por Faixa Etária (Porcentagem)')
plt.xlabel('Faixa Etária')
plt.ylabel('Porcentagem')

plt.legend(title='Raça/Cor', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

df_transformado.info()

df_transformado['Faixa Etária'].value_counts() #para entender a distribuição desse dataset

"""dividindo o dataset em masculino e feminino para análise

"""

df_final = df_transformado[['Faixa Etária','Sexo', 'Raca/Cor', 'Nome Profissão', 'Grau de Instrução', 'Estado Civil', 'Código da Topografia']]

# Dicionário de topografia
codigos_cancer = {
    'C01': 'Câncer da base da língua',
    'C10': 'Câncer da orofaringe',
    'C15': 'Câncer do Esôfago',
    'C16': 'Câncer de Estômago',
    'C18': 'Câncer de Cólon',
    'C20': 'Câncer de Reto',
    'C21': 'Câncer do ânus e do canal anal',
    'C22': 'Câncer de fígado e das vias biliares intra-hepáticas',
    'C23': 'Câncer da vesícula biliar',
    'C25': 'Câncer de Pâncreas',
    'C32': 'Câncer de Laringe',
    'C34': 'Câncer de Brônquios e Pulmões',
    'C44': 'Câncer de Pele',
    'C50': 'Câncer de Mama',
    'C54': 'Câncer do corpo do útero',
    'C60': 'Câncer de pênis',
    'C61': 'Câncer de Próstata',
    'C64': 'Câncer de rim, exceto pelve renal',
    'C67': 'Câncer de Bexiga',
    'C53': 'Câncer de Colo do Útero',
    'C56': 'Câncer de Ovário',
    'C71': 'Câncer de Encéfalo',
    'C73': 'Câncer da glândula tireoide',
    'C76': 'Câncer de outras localizações e de localizações mal definidas',
    'C77': 'Câncer secundário e não especificado dos gânglios linfáticos',
    'C80': 'Câncer sem especificação de localização',
    'C42': 'Câncer do Sistema Hematopoiético e Reticuloendotelial'
}

# df_final: todas as linhas, com o dicionário aplicado
df_final['Código da Topografia'] = df_final['Código da Topografia'].map(codigos_cancer).fillna(df_final['Código da Topografia'])

# df_geral: filtra C51–C63 ANTES do mapeamento (precisa dos códigos CXX)
# Então filtra a partir de df_transformado (antes do mapeamento)
df_geral = df_transformado[  # use o df antes do mapeamento
    (df_transformado['Código da Topografia'] < 'C51') |
    (df_transformado['Código da Topografia'] > 'C63')
].copy()
df_geral['Código da Topografia'] = df_geral['Código da Topografia'].map(codigos_cancer).fillna(df_geral['Código da Topografia'])

df_fem = df_final[df_final['Sexo'] == 'FEMININO' ]
df_masc = df_final[df_final['Sexo'] == 'MASCULINO']

df_fem.drop(columns=['Sexo'], inplace=True)
df_masc.drop(columns=['Sexo'], inplace=True)

df_masc

"""EXPORTAR O .CSV PARA MINHA PASTA DA IC NO DRIVE e continuar na parte 2 (
IC_Parte2.ipynb)

"""

df_masc.to_csv('/content/drive/MyDrive/IC/df_masc_porto_alegre.csv', index=False)
df_fem.to_csv('/content/drive/MyDrive/IC/df_fem_porto_alegre.csv', index=False)
df_geral.to_csv('/content/drive/MyDrive/IC/df_geral_porto_alegre.csv', index=False)