# -*- coding: utf-8 -*-
"""otimizada_IC_Parte2_fem.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15YMDUbHAhUfBEo76gc9_IkDvQLJHabbp

##Regra de Associação

### Filtrando o dataset por 'Raça/Cor'
"""

!pip install efficient-apriori

import warnings #para não printar o warning de time que dá quando usa para regra de associação mlextend
warnings.filterwarnings("ignore", category=DeprecationWarning)

import pandas as pd #exploração geral
import numpy as np #segmentação idades
# from mlxtend.preprocessing import TransactionEncoder #para deixar o df booleano
# from mlxtend.frequent_patterns import fpmax #para gerar regras de associação

from efficient_apriori import apriori

from google.colab import drive #importando da biblioteca do google colab a função drive para conseguir ler a tabela que eu subir no meu drive
drive.mount('/content/drive')

df_fem = pd.read_csv('/content/drive/MyDrive/IC/df_fem_belem.csv')

print(f"O dataset tem {len(df_fem)} linhas")

# Filtrar o DataFrame principal por 'Raca/Cor'
df_branca = df_fem[df_fem['Raca/Cor'] == 'BRANCO'].copy()
df_parda = df_fem[df_fem['Raca/Cor'] == 'PARDA'].copy()
df_preta = df_fem[df_fem['Raca/Cor'] == 'PRETA'].copy()

print(f"Número de registros para Raça Branca: {len(df_branca)}")
print(f"Número de registros para Raça Parda: {len(df_parda)}")
print(f"Número de registros para Raça Preta: {len(df_preta)}")

# Modififcar o suporte e a confiança para cada caso
def run_apriori_and_get_rules(dataframe, min_support=0.025, min_confidence=0.78, filter_topografia=True):
    """
    Executa o algoritmo Apriori em um DataFrame e retorna as regras de associação.

    Args:
        dataframe (pd.DataFrame): O DataFrame de entrada.
        min_support (float): O suporte mínimo para os itemsets frequentes.
        min_confidence (float): A confiança mínima para as regras.
        filter_topografia (bool): Se True, filtra as regras para incluir apenas
                                  aqueles com 'Código da Topografia' no antecedente ou consequente.

    Returns:
        pd.DataFrame: Um DataFrame contendo as regras de associação.
    """
    transacoes = []
    for index, row in dataframe.iterrows():
        transacao = []
        for column, value in row.items():
            if pd.notna(value):
                transacao.append(f"{column}_{value}")
        transacoes.append(tuple(transacao))

    # Rodar o apriori
    itemsets, rules = apriori(transacoes, min_support=min_support, min_confidence=min_confidence)

    regras_lista = []
    for rule in rules:
        antecedente = ', '.join(list(rule.lhs))
        consequente = ', '.join(list(rule.rhs))
        support = rule.support
        confidence = rule.confidence
        lift = rule.lift
        tamanho_antecedente = len(rule.lhs)

        regras_lista.append({
            'Antecedente': antecedente,
            'Consequente': consequente,
            'Suporte': support,
            'Confiança': confidence,
            'Lift': lift,
            'Tamanho do Antecedente': tamanho_antecedente
        })

    df_regras = pd.DataFrame(regras_lista)
    if not df_regras.empty:
        df_regras['Suporte'] = df_regras['Suporte'].round(3)
        df_regras['Confiança'] = df_regras['Confiança'].round(3)
        df_regras['Lift'] = df_regras['Lift'].round(3)
        df_regras = df_regras[df_regras['Lift'] > 1.0] # Adiciona o filtro para Lift > 1.0
        df_regras = df_regras.sort_values(by='Tamanho do Antecedente', ascending=False)

    if filter_topografia:
        df_regras = df_regras[df_regras['Antecedente'].str.contains('Código da Topografia') |
                              df_regras['Consequente'].str.contains('Código da Topografia')]

    return df_regras

df_regras_branca = run_apriori_and_get_rules(df_branca)
print("Regras de Associação para Raça Branca:")
display(df_regras_branca)

df_regras_parda = run_apriori_and_get_rules(df_parda)
print("Regras de Associação para Raça Parda:")
display(df_regras_parda)

df_regras_preta = run_apriori_and_get_rules(df_preta)
print("Regras de Associação para Raça Preta:")
display(df_regras_preta)

from google.colab import sheets
sheet = sheets.InteractiveSheet(df=df_regras_preta)

# Supondo que o suporte da regra seja 0.01
suporte = 0.018
total_registros = len(df_parda)
quantidade_absoluta = suporte * total_registros

print(f"Total de registros na base: {total_registros}")
print(f"A regra aparece em aproximadamente {round(quantidade_absoluta)} registros.")

"""Aqui é só mudar o fim do .csv para cidade a ser analisada"""